### PR TITLE
- Refined controller model and cleaned up architecture

### PR DESCRIPTION
**Pull request by danielmsheliza**
•	The xy position error which will be used to achieve stable hover by means of attitude actuation was implemented in the outer loop which is inconsistent with the functions of the outer loop which is altitude control. Check that that has been moved to the inner loop and the simulation works as it should
•	There was a mismatch in reference frames between the desired and the sensor-measured xy velocities.
where the desired xy velocity, calculated using xy position error, is in the MFWF body frame and the sensor-measured xy velocity is in the inertial reference frame. Chack that that is fixed now as I implemented the same 2D Inertial-to-body frame rotation matrix used in orienting the desired xy velocity.

### CODE REVIEW

**Comment by HendrikseL** [comment]
Your changes are good and the model is running.

I do have a few questions though:

1. I believe these tags should be sensor xy_vel is the v a typo?
image

2.  I was under the impression that the outer loop controls all things to do with position, are the x and y errors:
image

had something to do with flyer position? If in the future when x and y maneuvers how would the part I highlighted in yellow be changed to reflect the new controller position?

**Comment by danielmsheliza** [comment]
Thanks for the review. I will answer your questions below:

1. You are right, it is a typo, it is meant to be "xy_vel" instead of "xv_vel"

2. The outer loop is only used for Z position control (altitude). The inner loop is used for maintaining stable hover and uses the xy error for position control to achieve this.
       2ii. This architecture might still change if we are to implement x and y maneuvers in the future

I hope I have answered your questions.

**Comment by HendrikseL** [comment]
Yes, you have. In that case all is good and I think it's ready to merge when a second review comes through. Good work here.

**Comment by colinmenzel** [comment]
All the changes look good and everything works. Seems ready to merge. Just don't forget to fix that top level change thing.

**Pull request merged**
